/**
 * Ländervorwahlen für Telefonnummern (ITU E.164).
 * Deutschland als erstes für Default-Auswahl.
 */
export const countryCodes = [
  { code: "DE", dialCode: "+49", name: "Deutschland" },
  { code: "AT", dialCode: "+43", name: "Österreich" },
  { code: "CH", dialCode: "+41", name: "Schweiz" },
  { code: "AF", dialCode: "+93", name: "Afghanistan" },
  { code: "AL", dialCode: "+355", name: "Albanien" },
  { code: "DZ", dialCode: "+213", name: "Algerien" },
  { code: "AD", dialCode: "+376", name: "Andorra" },
  { code: "AO", dialCode: "+244", name: "Angola" },
  { code: "AG", dialCode: "+1268", name: "Antigua und Barbuda" },
  { code: "AR", dialCode: "+54", name: "Argentinien" },
  { code: "AM", dialCode: "+374", name: "Armenien" },
  { code: "AU", dialCode: "+61", name: "Australien" },
  { code: "AZ", dialCode: "+994", name: "Aserbaidschan" },
  { code: "BS", dialCode: "+1242", name: "Bahamas" },
  { code: "BH", dialCode: "+973", name: "Bahrain" },
  { code: "BD", dialCode: "+880", name: "Bangladesch" },
  { code: "BB", dialCode: "+1246", name: "Barbados" },
  { code: "BY", dialCode: "+375", name: "Belarus" },
  { code: "BE", dialCode: "+32", name: "Belgien" },
  { code: "BZ", dialCode: "+501", name: "Belize" },
  { code: "BJ", dialCode: "+229", name: "Benin" },
  { code: "BT", dialCode: "+975", name: "Bhutan" },
  { code: "BO", dialCode: "+591", name: "Bolivien" },
  { code: "BA", dialCode: "+387", name: "Bosnien und Herzegowina" },
  { code: "BW", dialCode: "+267", name: "Botswana" },
  { code: "BR", dialCode: "+55", name: "Brasilien" },
  { code: "BN", dialCode: "+673", name: "Brunei" },
  { code: "BG", dialCode: "+359", name: "Bulgarien" },
  { code: "BF", dialCode: "+226", name: "Burkina Faso" },
  { code: "BI", dialCode: "+257", name: "Burundi" },
  { code: "CV", dialCode: "+238", name: "Kap Verde" },
  { code: "KH", dialCode: "+855", name: "Kambodscha" },
  { code: "CM", dialCode: "+237", name: "Kamerun" },
  { code: "CA", dialCode: "+1", name: "Kanada" },
  { code: "CF", dialCode: "+236", name: "Zentralafrikanische Republik" },
  { code: "TD", dialCode: "+235", name: "Tschad" },
  { code: "CL", dialCode: "+56", name: "Chile" },
  { code: "CN", dialCode: "+86", name: "China" },
  { code: "CO", dialCode: "+57", name: "Kolumbien" },
  { code: "KM", dialCode: "+269", name: "Komoren" },
  { code: "CG", dialCode: "+242", name: "Kongo" },
  { code: "CD", dialCode: "+243", name: "Demokratische Republik Kongo" },
  { code: "CR", dialCode: "+506", name: "Costa Rica" },
  { code: "HR", dialCode: "+385", name: "Kroatien" },
  { code: "CU", dialCode: "+53", name: "Kuba" },
  { code: "CY", dialCode: "+357", name: "Zypern" },
  { code: "CZ", dialCode: "+420", name: "Tschechien" },
  { code: "DK", dialCode: "+45", name: "Dänemark" },
  { code: "DJ", dialCode: "+253", name: "Dschibuti" },
  { code: "DM", dialCode: "+1767", name: "Dominica" },
  { code: "DO", dialCode: "+1809", name: "Dominikanische Republik" },
  { code: "EC", dialCode: "+593", name: "Ecuador" },
  { code: "EG", dialCode: "+20", name: "Ägypten" },
  { code: "SV", dialCode: "+503", name: "El Salvador" },
  { code: "GQ", dialCode: "+240", name: "Äquatorialguinea" },
  { code: "ER", dialCode: "+291", name: "Eritrea" },
  { code: "EE", dialCode: "+372", name: "Estland" },
  { code: "SZ", dialCode: "+268", name: "Eswatini" },
  { code: "ET", dialCode: "+251", name: "Äthiopien" },
  { code: "FJ", dialCode: "+679", name: "Fidschi" },
  { code: "FI", dialCode: "+358", name: "Finnland" },
  { code: "FR", dialCode: "+33", name: "Frankreich" },
  { code: "GA", dialCode: "+241", name: "Gabun" },
  { code: "GM", dialCode: "+220", name: "Gambia" },
  { code: "GE", dialCode: "+995", name: "Georgien" },
  { code: "GH", dialCode: "+233", name: "Ghana" },
  { code: "GR", dialCode: "+30", name: "Griechenland" },
  { code: "GD", dialCode: "+1473", name: "Grenada" },
  { code: "GT", dialCode: "+502", name: "Guatemala" },
  { code: "GN", dialCode: "+224", name: "Guinea" },
  { code: "GW", dialCode: "+245", name: "Guinea-Bissau" },
  { code: "GY", dialCode: "+592", name: "Guyana" },
  { code: "HT", dialCode: "+509", name: "Haiti" },
  { code: "HN", dialCode: "+504", name: "Honduras" },
  { code: "HK", dialCode: "+852", name: "Hongkong" },
  { code: "HU", dialCode: "+36", name: "Ungarn" },
  { code: "IS", dialCode: "+354", name: "Island" },
  { code: "IN", dialCode: "+91", name: "Indien" },
  { code: "ID", dialCode: "+62", name: "Indonesien" },
  { code: "IR", dialCode: "+98", name: "Iran" },
  { code: "IQ", dialCode: "+964", name: "Irak" },
  { code: "IE", dialCode: "+353", name: "Irland" },
  { code: "IL", dialCode: "+972", name: "Israel" },
  { code: "IT", dialCode: "+39", name: "Italien" },
  { code: "CI", dialCode: "+225", name: "Elfenbeinküste" },
  { code: "JM", dialCode: "+1876", name: "Jamaika" },
  { code: "JP", dialCode: "+81", name: "Japan" },
  { code: "JO", dialCode: "+962", name: "Jordanien" },
  { code: "KZ", dialCode: "+7", name: "Kasachstan" },
  { code: "KE", dialCode: "+254", name: "Kenia" },
  { code: "KI", dialCode: "+686", name: "Kiribati" },
  { code: "KP", dialCode: "+850", name: "Nordkorea" },
  { code: "KR", dialCode: "+82", name: "Südkorea" },
  { code: "KW", dialCode: "+965", name: "Kuwait" },
  { code: "KG", dialCode: "+996", name: "Kirgisistan" },
  { code: "LA", dialCode: "+856", name: "Laos" },
  { code: "LV", dialCode: "+371", name: "Lettland" },
  { code: "LB", dialCode: "+961", name: "Libanon" },
  { code: "LS", dialCode: "+266", name: "Lesotho" },
  { code: "LR", dialCode: "+231", name: "Liberia" },
  { code: "LY", dialCode: "+218", name: "Libyen" },
  { code: "LI", dialCode: "+423", name: "Liechtenstein" },
  { code: "LT", dialCode: "+370", name: "Litauen" },
  { code: "LU", dialCode: "+352", name: "Luxemburg" },
  { code: "MO", dialCode: "+853", name: "Macau" },
  { code: "MG", dialCode: "+261", name: "Madagaskar" },
  { code: "MW", dialCode: "+265", name: "Malawi" },
  { code: "MY", dialCode: "+60", name: "Malaysia" },
  { code: "MV", dialCode: "+960", name: "Malediven" },
  { code: "ML", dialCode: "+223", name: "Mali" },
  { code: "MT", dialCode: "+356", name: "Malta" },
  { code: "MH", dialCode: "+692", name: "Marshallinseln" },
  { code: "MR", dialCode: "+222", name: "Mauretanien" },
  { code: "MU", dialCode: "+230", name: "Mauritius" },
  { code: "MX", dialCode: "+52", name: "Mexiko" },
  { code: "FM", dialCode: "+691", name: "Mikronesien" },
  { code: "MD", dialCode: "+373", name: "Moldau" },
  { code: "MC", dialCode: "+377", name: "Monaco" },
  { code: "MN", dialCode: "+976", name: "Mongolei" },
  { code: "ME", dialCode: "+382", name: "Montenegro" },
  { code: "MA", dialCode: "+212", name: "Marokko" },
  { code: "MZ", dialCode: "+258", name: "Mosambik" },
  { code: "MM", dialCode: "+95", name: "Myanmar" },
  { code: "NA", dialCode: "+264", name: "Namibia" },
  { code: "NR", dialCode: "+674", name: "Nauru" },
  { code: "NP", dialCode: "+977", name: "Nepal" },
  { code: "NL", dialCode: "+31", name: "Niederlande" },
  { code: "NZ", dialCode: "+64", name: "Neuseeland" },
  { code: "NI", dialCode: "+505", name: "Nicaragua" },
  { code: "NE", dialCode: "+227", name: "Niger" },
  { code: "NG", dialCode: "+234", name: "Nigeria" },
  { code: "MK", dialCode: "+389", name: "Nordmazedonien" },
  { code: "NO", dialCode: "+47", name: "Norwegen" },
  { code: "OM", dialCode: "+968", name: "Oman" },
  { code: "PK", dialCode: "+92", name: "Pakistan" },
  { code: "PW", dialCode: "+680", name: "Palau" },
  { code: "PS", dialCode: "+970", name: "Palästina" },
  { code: "PA", dialCode: "+507", name: "Panama" },
  { code: "PG", dialCode: "+675", name: "Papua-Neuguinea" },
  { code: "PY", dialCode: "+595", name: "Paraguay" },
  { code: "PE", dialCode: "+51", name: "Peru" },
  { code: "PH", dialCode: "+63", name: "Philippinen" },
  { code: "PL", dialCode: "+48", name: "Polen" },
  { code: "PT", dialCode: "+351", name: "Portugal" },
  { code: "QA", dialCode: "+974", name: "Katar" },
  { code: "RO", dialCode: "+40", name: "Rumänien" },
  { code: "RU", dialCode: "+7", name: "Russland" },
  { code: "RW", dialCode: "+250", name: "Ruanda" },
  { code: "KN", dialCode: "+1869", name: "St. Kitts und Nevis" },
  { code: "LC", dialCode: "+1758", name: "St. Lucia" },
  { code: "VC", dialCode: "+1784", name: "St. Vincent und die Grenadinen" },
  { code: "WS", dialCode: "+685", name: "Samoa" },
  { code: "SM", dialCode: "+378", name: "San Marino" },
  { code: "ST", dialCode: "+239", name: "São Tomé und Príncipe" },
  { code: "SA", dialCode: "+966", name: "Saudi-Arabien" },
  { code: "SN", dialCode: "+221", name: "Senegal" },
  { code: "RS", dialCode: "+381", name: "Serbien" },
  { code: "SC", dialCode: "+248", name: "Seychellen" },
  { code: "SL", dialCode: "+232", name: "Sierra Leone" },
  { code: "SG", dialCode: "+65", name: "Singapur" },
  { code: "SK", dialCode: "+421", name: "Slowakei" },
  { code: "SI", dialCode: "+386", name: "Slowenien" },
  { code: "SB", dialCode: "+677", name: "Salomonen" },
  { code: "SO", dialCode: "+252", name: "Somalia" },
  { code: "ZA", dialCode: "+27", name: "Südafrika" },
  { code: "SS", dialCode: "+211", name: "Südsudan" },
  { code: "ES", dialCode: "+34", name: "Spanien" },
  { code: "LK", dialCode: "+94", name: "Sri Lanka" },
  { code: "SD", dialCode: "+249", name: "Sudan" },
  { code: "SR", dialCode: "+597", name: "Suriname" },
  { code: "SE", dialCode: "+46", name: "Schweden" },
  { code: "SY", dialCode: "+963", name: "Syrien" },
  { code: "TW", dialCode: "+886", name: "Taiwan" },
  { code: "TJ", dialCode: "+992", name: "Tadschikistan" },
  { code: "TZ", dialCode: "+255", name: "Tansania" },
  { code: "TH", dialCode: "+66", name: "Thailand" },
  { code: "TL", dialCode: "+670", name: "Osttimor" },
  { code: "TG", dialCode: "+228", name: "Togo" },
  { code: "TO", dialCode: "+676", name: "Tonga" },
  { code: "TT", dialCode: "+1868", name: "Trinidad und Tobago" },
  { code: "TN", dialCode: "+216", name: "Tunesien" },
  { code: "TR", dialCode: "+90", name: "Türkei" },
  { code: "TM", dialCode: "+993", name: "Turkmenistan" },
  { code: "TV", dialCode: "+688", name: "Tuvalu" },
  { code: "UG", dialCode: "+256", name: "Uganda" },
  { code: "UA", dialCode: "+380", name: "Ukraine" },
  { code: "AE", dialCode: "+971", name: "Vereinigte Arabische Emirate" },
  { code: "GB", dialCode: "+44", name: "Vereinigtes Königreich" },
  { code: "US", dialCode: "+1", name: "Vereinigte Staaten" },
  { code: "UY", dialCode: "+598", name: "Uruguay" },
  { code: "UZ", dialCode: "+998", name: "Usbekistan" },
  { code: "VU", dialCode: "+678", name: "Vanuatu" },
  { code: "VA", dialCode: "+379", name: "Vatikanstadt" },
  { code: "VE", dialCode: "+58", name: "Venezuela" },
  { code: "VN", dialCode: "+84", name: "Vietnam" },
  { code: "YE", dialCode: "+967", name: "Jemen" },
  { code: "ZM", dialCode: "+260", name: "Sambia" },
  { code: "ZW", dialCode: "+263", name: "Simbabwe" },
] as const;
